name: Lint

on:
  pull_request:
    branches:
      - fuzz-tester

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19' # Use the Go version required for your project

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2

      - name: Identify Modified Files
        id: modified_files
        run: |
          MODIFIED_FILES=$(git diff --name-only origin/main -- '*.go')
          echo "::set-output name=files::$MODIFIED_FILES"

      - name: Run golangci-lint
        if: steps.modified_files.outputs.files != ''
        run: |
          echo "${{ steps.modified_files.outputs.files }}" | xargs golangci-lint run
