name: Lint

on:
  pull_request:
    branches:
      - fuzz-tester  # Add the specific branch you want to use

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0             # Fetch all history for diffing
          ref: fuzz-tester           # Ensure the fuzz-tester branch is available

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.19' # Adjust for your project requirements

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2

      - name: Identify Modified Files
        id: modified_files
        run: |
          # Fetch main and other branches to ensure origin/fuzz-tester is available
          git fetch origin main
          MODIFIED_FILES=$(git diff --name-only origin/fuzz-tester -- '*.go')
          echo "::set-output name=files::$MODIFIED_FILES"

      - name: Run golangci-lint
        if: steps.modified_files.outputs.files != ''
        run: |
          echo "${{ steps.modified_files.outputs.files }}" | xargs golangci-lint run
